spring.application.name=Lost and Found Campus Portal

server.port=9090
spring.datasource.url=jdbc:mysql://localhost:3306/lost&found
spring.datasource.username=root
spring.datasource.password=12345678

spring.security.user.name=sarawer
spring.security.user.password=1234

spring.jpa.hibernate.ddl-auto=update
